- src/objects.c
Hi,
My coleague, Gianni Ciolli, hit a bug with "PAUSE db" where pgbouncer allows new client connection to actually connect to the paused server. It works fine with plain "PAUSE", just "PAUSE db" is affected.
This is because "PAUSE db" does not set cf_pause_mode but only db->db_paused, which by itself is correct behaviour but then the find_server function completely ignores the db->db_paused setting.
So here is one liner to fix that.
> Don't allow newserver connections when PAUSE <db> was issued.

- Makefile
- include/bouncer.h
Debian wants debug symbols for all builds (the binaries are stripped by
debhelper's dh_strip), but the "(compiled by...)" information added for
debug builds defeats the goal to make builds reproducible on the binary
level. Fix by dropping the DBGVER information which doesn't serve any
purpose if the build output is byte-identical on rebuild.
https://wiki.debian.org/ReproducibleBuilds
> Make build reproducible by dropping DBGVER handling

- src/main.c
When starting pgbouncer with -d (which is for example what the default is on a CentOS platform when using yum.postgresql.org at least), the pam authentication method does not work. Looking at it with gdb, it seems the background thread required for it is simply not created.
When starting without -d it works fine -- so just modifying the systemd startup file to not be a forking server works. But it seems there's an issue somewhere in pgbouncer as well, and it's 100% reproducible outside a systemd environment.
My guess is that the pam_init() call is happening in the process than then goes away, and it needs to happen after the go_daemon() call. 
The following patch *seems* to work, but I'd appreciate a review from somebody who knows pgbouncer better than me. In particular, there may be an …
> Make pam_init happen in the child process when forking

- src/admin.c
- src/objects.c
Don't send ReadyForQuery on main_connection as it may cause clients to get out of sync. Drop the connection for idle clients.
https://github.com/pgbouncer/pgbouncer/issues/141
> Don't send ReadyForQuery on main_connection for CancelQuery requests

- COPYRIGHT
It's not strictly required, but it's useful metadata, and part of the recommended license template text (see http://choosealicense.com/licenses/isc/ and https://opensource.org/licenses/isc-license)
> add license title

- src/admin.c
Higher resolution maxwait allows for earlier detection of issues and better measurement of performance tuning efforts.
This PR enables that behaviour by exposing the full resolution max-wait value in the SHOW POOLS command. In order to both maintain backwards compatibility and keep everything as 32 bit integers, this adds only the sub-second microseconds part of the time that was previously being truncated. Existing statistics collectors can continue reading the `maxwait` column at second resolution without interruption, while clients that need the full precision can treat the `maxwait` + `maxwait_us` pair as a `struct timeval` and use all the normal tools for dealing with that type of time.
> Add a maxwait microseconds column to SHOW POOLS.

- doc/config.rst
- include/bouncer.h
As the postgres password is hashed it can easily become bigger than 64 characters on some deployments. 
Some providers (for example Heroku) have begun to adopt improved security policies for the postgres credentials generated automatically by their systems. In the situation where the credential is bigger than 64 characters, pgbouncer will simply read an incomplete password from the configuration file and then try to use it for authentication, resulting on a log message stating that the password authentication has failed, as below:
`WARNING server login failed: FATAL password authentication failed for user "blablatest"`
There is no indication whatsoever that the problem is actually located on the pgbouncer side. This small change increases the size of the password buffer to cope with …
> Increased maximum length for postgres password

- NEWS.rst
- doc/usage.rst
- src/admin.c
The parameter is called auth_type, not auth_mode.
> Fix incorrect references to auth_mode

- src/stats.c
Change "b/s" to "B/s", because the units are bytes.
> Corrects bits vs bytes

- doc/usage.rst
- include/bouncer.h
- include/stats.h
- src/admin.c
- src/client.c
- src/objects.c
- src/server.c
- src/stats.c
The documentation claimed avg_query tracks average query duration,
but it was only updated when switching into 'idle' state. So in
transaction or session pooling modes, it was actually the duration
of the whole transaction, including 'idle in transaction' time and
time spen executing (multiple) queries.
This was causing confusion, e.g. when the application was keeping
transactions open without executing any queries. In that case the
avg_query metric was increasing although the database was handling
queries just fine (without any slow-down).
Instead of just fixing the avg_query metric, it seems quite useful
to have timing data both for queries and transactions. So this
patch replaces
- total_query_time
- avg_query
with
- total_xact_time
- total_query_time
- avg_xact_time
- avg_query_time …
> Track separate stats for queries and transactions

- src/hba.c
Parsing the HBA config files is being done a bit too quiet.  It took me a lot of time sorting out an existing installation to figure out there was a failing line in the pgbouncer hba config file.  Logging a few warnings would help a lot in understanding where the problem is.   Hope this helps others.
> add clues for sysadmin concerning HBA issues

- doc/config.rst
- etc/pgbouncer.ini
Instead of using arbritary values, use the default values. It is to avoid surprises if you just remove comment character (;). I also did some cosmetic changes. While at it, add some default information for
auth_user.
> Use default values in config file

- src/hba.c
This addresses two bugs which are perhaps not terribly likely to happen:
* If the `fopen()` call fails `parse_namefile()` frees the filename buffer `fn`, and the caller does the same. Avoid freeing in `parse_namefile()` and leave the cleanup to the caller.
* If we fail to `calloc()` the `rule` buffer, going to `failed:` will dereference `rule` via the `rule_free()` call. Avoid by returning `false` directly and bypass the `failed:` block.
> Fix a double-free and a NULL pointer deref

- doc/config.rst
- etc/pgbouncer.ini
The correct per pool parameter is reserve_pool. The global parameter is named
reserve_pool_size.
While at it, document reserve_pool parameter.
> Fix reserve_pool parameter

- include/bouncer.h
- src/objects.c
If postgres restarts while there are N cancellations in the queue, pgbouncer is currently unavailable for at least N*`server_login_retry` because it uses every new connection for one queued cancellation and then waits `server_login_retry` before opening a new connection because the `last_connect_failed` flag is still set to 1. This can lead to prolonged downtime.
This changes fixes the issue by introducing a `last_login_failed` flag. The `last_connect_failed` flag is now reset when a cancellation succeeds, such that `launch_new_connection` no longer waits if pgbouncer manages to connect, but has queued cancellations. The `last_login_failed` flag has the same semantics as the `last_connect_failed` flag had previously, such that `check_fast_fail` still rejects connections when there are no …
> Do not wait server_login_retry for next connect if cancellation succeeds

- src/client.c
After a PostgreSQL reload, the backend could inform the frontend about configuration changes by sending some ParameterStatus messages together with the usual login query response. These messages can be safely ignored in the login query response handler.
Closes: #220
> Avoid 'unexpected response from login query' after a postgres reload

- test/ssl/newsite.sh
If the test certs expire later than 2038, the conversion to time_t
overflows on 32bit and we get spurious handshake failures.
Fixes: #434
> test: shorten lifetime of certificates to avoid overflowing 32bit time_t

- test/test.sh
Some CI environments run without $USER set. Fix by defaulting to `id -un`.
(Seen on salsa.debian.org.)
> Set USER if unset

- src/main.c
This fixes a simple typo in the log output where it says SIGUSR1 instead of SIGUSR2.
> Fix typo in handle_sigusr2()

- src/hba.c
If fails to load the HBA fails logs the error explicitly
> Log when fails loading the hba file

- src/client.c
- src/objects.c
This avoids log spam when monitoring systems just open a TCP/IP
connection but don't send anything before disconnecting.
closes #323
> Don't log anything if client disconnects immediately

- doc/usage.md
- include/bouncer.h
- src/admin.c
- src/main.c
The default values are available but weren't exposed.
> Add default value to SHOW CONFIG

- src/janitor.c
As described in #245 this is the first patch in a series of patches to improve the cancelation of a backend when pgbouncer is involved.
In this patch we introduce the launching of a new connection when cancelations are queued. There already was a loop that would calculate if a new connection should be launched if there was a client waiting for a backend. By not launching connections for cancelations we have observed very chaotic behaviour where a bunch (1200) of cancelations are flushed at once when a new connection was established. These cancelations came to pgbouncer at a moment when no new connections could be launched as other wise they would have been consumed from the queue directly after the connection gets established.
cancelation queueing and connection launch: …
> launch new connections when cancel requests are queued

- .cirrus.yml
Since Travis CI will apparently shut down its free tier for open-source projects, here is a replacement using Cirrus CI. For now, it's meant to be a one-for-one replacement (except the builds for different architectures, which Cirrus CI doesn't support). I only dropped the ElectricFence builds, since those don't appear to work on newer systems anymore, and Valgrind can pretty much do the same thing.
> Cirrus CI support

- include/bouncer.h
- include/pktbuf.h
- src/admin.c
- src/client.c
- src/dnslookup.c
- src/janitor.c
- src/loader.c
- src/objects.c
- src/pam.c
- src/pktbuf.c
- src/pooler.c
- src/proto.c
- src/server.c
- test/asynctest.c
Some code was using 0 and 1, although most newer code seems to prefer
true and false.
Also, turn the declaration of some variables from integer to bool if
they are actually used as Booleans.
> Use true and false for bool constants consistently

- src/dnslookup.c
This PR fixes the Windows build with `--with-cares`.
> c-ares on Windows

- include/loader.h
- src/loader.c
- src/objects.c
The previous code did error checking on the database connection string and user settings in the `[database]` and `[user]` sections, but `parse_database()` and `parse_user()` still returned true in case of error, so these errors were just logged and nothing else happened.  By returning false, we get the normal behavior for parsing the configuration file: on startup, you get a fatal error, on reload, you just get messages.  This also requires polishing the error messages a bit, since some of them were talking about "skipping" invalid settings, which isn't what happens anymore.
> Tighten error handling of database and user parameters

- src/server.c
Running multiple queries in a pipelined way would trigger the dreaded
"FIXME: query end, but query_start == 0" log messages because when the
first query finishes, we reset the query_start, and then the return of
the second query gets upset.  To fix that, only compute the time when
all queries in flight have finished.
solution by @vonzshik
closes #39, closes #144, closes #215, closes #277, closes #376, closes #565
> Fixed multiple sequential queries logging

- src/dnslookup.c
We have a failed DNS lookup, and even log as such at the debug level,
but then instruct the DNS result function that our result status was a
success, meaning we won't log_warning that failure as well as incorrect
update the cached results and ttl.
> Fix DNS error treated as success

- doc/config.md
- doc/usage.md
- include/bouncer.h
- src/admin.c
- src/janitor.c
- src/loader.c
- src/objects.c
This feature allows to set min_pool_size per database. The current
behavior uses the same min_pool_size setting for all databases. It could
not be suitable for some databases that has a different access pattern.
Let's say one database need a minimum number of connections to handle a
burst of connections in order to not increase the response time.
However, the other databases doesn't need such requirement. Hence, this
feature reduces the number of connections open by pgbouncer.
Closes #91
> Set minimum pool size per database

- doc/usage.md
- src/admin.c
This commit includes a new metricto SHOW POOLS command: cl_cancel_req.
It informs the number of clients that request query cancellations.
> Include number of query cancellations into SHOW POOLS

- src/client.c
As a general principle, we shouldn't expose that kind of information
to clients before they are authenticated.
Also, if SCRAM pass-through is used and the password in auth_file is
updated, server connections will start to fail becaues the ClientKey
and ServerKey are outdated.  In that case, we need to allow new
clients to log in to pgbouncer, since that updates those values.
We could move the check to finish_client_login(), so it happens during
login but after authentication.  But in practice, the check in
find_server() will soon be executed anyway, unless the client just
logs in and does nothing.
This effectively reverts 760760d62b71b773aca6efef8024039501819210.
> Don't apply fast-fail at connect time

- doc/config.md
IMO the "unused" term was a bit confusing.
> Clarify 'server_lifetime' description

- include/bouncer.h
- src/client.c
- src/objects.c
- test/test.sh
On client login, when a database does not exist, don't immediately respond with "no such database", because we don't want hostile clients to be able to probe what databases exist.  Instead, do the authentication first and then respond about the database.
This is similar to 7f7ff12a4288d9ab52154c7229afc0186f8196bb, but for databases.
> Mock authentication for missing databases

- .cirrus.yml
- doc/config.md
- include/bouncer.h
- src/objects.c
- test/test.ini
- test/test.sh
A common feature request is to have PgBouncer do some kind of load-balancing or round-robin between a set of backend servers. This is currently possible by using DNS to resolve a host name to multiple addresses. But many people don't want to use DNS.
This patch implements a host list on the configuration level. So you can specify, for example
host=server1,server2,server3
where the "serverN" can be IP addresses or host names as usual. On connection, PgBouncer will simply rotate between them.
Thoughts?
> Allow comma-separated host list

- .cirrus.yml
It seems the default Alpine image doesn't have bash installed anymore,
but the test.sh script requires it. This installs it on CI.
An example of a failed CI run can be found here: https://cirrus-ci.com/task/6439380507164672
> CI: Install bash on Alpine

- src/sbuf.c
If the dst socket is closed, `sbuf_send_pending` will fail but not mark the operation as failed.
It will then retry repeatedly, consuming a lot of CPU until pgbouncer is restarted.
> Fail sbuf_send_pending operation if dst socket is closed

- include/bouncer.h
The issue is described in [Issue #746](https://github.com/pgbouncer/pgbouncer/issues/746). Copying the description here:
**Description:**
The feature introduced in v-1.17 which enables pgbouncer to round-robin over a comma-separated host list has a bug, which results in connections to a client defined with a host list being re-routed to the UNIX socket path instead (/tmp). Details and repro below:
In the following block of [code](https://github.com/pgbouncer/pgbouncer/blob/275c7cca9209881aa9b045bf6ca908e76fdb359e/src/objects.c#L1078) responsible for parsing the host-list and round-robining across the hosts:
```
/* host list? */
if (db->host && strchr(db->host, ',')) {
int count = 1;
int n;
for (const char *p = db->host; *p; p++)
if (*p == ',')
count++;
host_copy = xstrdup(db->host);
for …
```
> Fix for int16 overflow bug causing connection to get re-routed to UNIX socket

- src/client.c
- src/objects.c
- test/test.sh
We were seeing segfaults occur when using scram authentication to connect to non-existent databases. Looks like the issue arises when attempting to save the Scram authentication keys. This PR adds a check that the DB isn't fake before attempting to save the credentials
> Prevent Segfault when connecting to non-existent DB with Scram Authentication

- doc/config.md
This PR adds an example of a multiple-valued `ignore_startup_parameters`. The syntax for an array of options isn't obvious, and can result in misconfigurations. For example, see the following 2 issues on zalando/postgres-operator:
- zalando/postgres-operator#984
- zalando/postgres-operator#1029
> Add example of multiple values for ignore_startup_parameters

- doc/usage.md
During investigation of client wait time we came across several pieces of documentation that were either incomplete, confusing, or just plain wrong. This fixes several of those.
I'd like mark the existing `avg_wait_time` calculation as deprecated, but I'll open up something separate for that (because the alternative is fixing it).
> Fix incorrect/confusing docs

- include/bouncer.h
The doc updates in #726 made clear that some stats fields of PgSocket
were only used for clients not servers. This makes this also clear in
the code comments for those fields of PgSocket.
> Make a few fields in PgSocket client only

- include/objects.h
- src/janitor.c
- src/objects.c
- src/takeover.c
- test/test.ini
- test/test.sh
- test/userlist.txt
This should prevent us from evicting older idle connections unnecessarily if the max connection limit for the user or db has been reached.
This should address issue: https://github.com/pgbouncer/pgbouncer/issues/647
I have ran `test/test.sh` and all tests are passing (including two newly added ones).
I have also tested locally reverting the checks I added to janitor and verified that the newly added tests fail.
> Don't evict connections to achieve min_pool_size

- doc/usage.md
- include/bouncer.h
- include/objects.h
- src/admin.c
- src/janitor.c
- src/objects.c
- src/server.c
- test/test.sh
Cancel requests happen out of band with regular queries. Because
PgBouncer reuses server connections across clients its possible to get
race conditions here if you're not careful.
Without this patch there were two possibilities for a race condition
where a cancel request for client A could cancel a query that was sent
by client B. These race conditions happened when:
1. A cancel request on client A was forwarded to the server only after
the server was reused by another client.
2. A cancel request for client A was already forwarded to the server,
but not yet handled by the server and then the server was reused for
client B.
The first race conditions was especially likely if connection
establishment takes a while, for example because of TLS roundtrips.
Because a new connection needs to be …
> Handle race condition between cancel requests and server reuse

- doc/usage.md
- src/admin.c
When debugging issues it can be useful to see the clients and servers
that are involved in cancel requests.
> Add cancel requests to SHOW CLIENTS/SERVERS

- doc/usage.md
- include/bouncer.h
- src/admin.c
- src/janitor.c
- src/objects.c
After merging #717 it was noted that the `wait_cancels` name was quite
confusing. This changes that name to `being_canceled`. This makes it
more clear that this is not a server that is canceling itself, but
instead it's the target of a cancellation request.
Another option would be to rename it to waiting_cancel to be symetric 
with the client state. However, not being symetric is kind of the point 
of the newly suggested name. 
sv_wait_cancel would suggest that it's waiting for a cancel that it sent itself:
- active_cancel_req_list, is a list of clients that are sending a cancel themselves
- waiting_cancel_req_list, is a list of clients that are waiting for a server connection needed to for the cancel
- active_cancel_server_list, is the list of server connections on which a cancel is …
> Rename wait_cancels state to being_canceled

- .cirrus.yml
While debugging some unrelated CI issue I noticed this message in the
interface:
> We are sunsetting support for Intel-based macOS instances! Please migrate before January 1st 2023.
This updates our config to migrate to the new macOS instances.
> CI: Use new MacOS instance

- .appveyor.yml
- .cirrus.yml
- .gitignore
- doc/Makefile
To speed up compilation. All CI machines have 2 or 4 cores, it's unclear
if those numbers include hyperthreads or not. For simplicity we start
using 4 threads everywhere. In my experience it's much worse if you less
parallelism than can be handled, but having a bit more doesn't matter
too much for the total compilation time. Also if any of these tasks are
I/O bound instead of CPU bound, then you want more parallelism than your
amount of cores anyway.
As an example of speedup this improves the speed of the build step 
on windows CI from 3 minutes to 2 minutes.
> Run make in CI in parallel

- src/sbuf.c
On an unrelated PR a memory leak was reported by CI on a TLS test.
```
==11838== VALGRIND-ERROR-BEGIN
==11838== 71,890 (112 direct, 71,778 indirect) bytes in 1 blocks are definitely lost in loss record 178 of 178
==11838==    at 0x483DD99: calloc (in /usr/lib/x86_64-linux-gnu/valgrind/vgpreload_memcheck-amd64-linux.so)
==11838==    by 0x15B06E: tls_new (tls.c:240)
==11838==    by 0x16210B: tls_server_conn (tls_server.c:47)
==11838==    by 0x16248E: tls_accept_fds (tls_server.c:141)
==11838==    by 0x1380EB: sbuf_tls_accept (sbuf.c:1127)
==11838==    by 0x11E15A: handle_client_startup (client.c:729)
==11838==    by 0x11EF17: client_proto (client.c:1041)
==11838==    by 0x136069: sbuf_call_proto (sbuf.c:390)
==11838==    by 0x136B58: sbuf_process_pending (sbuf.c:583)
==11838==    by …
```
> Fix possible memory leak on TLS handshake failure

- doc/usage.md
- src/admin.c
- test/test.sh
This new command exposes the current PgBouncer state which can be:
active, pause or suspend (see PauseMode). Although it is possible to
obtain this state looking at SHOW DATABASES, you have to process
multiple entries to discover the global state; it seems a fragile
solution. PgBouncer has an internal variable that knows the current
state so let's expose it.
Closes #528
> SHOW STATE command

- src/main.c
- src/system.c
Provide suitable FATAL messages for unsupported options on Windows.
> Unsupported Windows command line options

- .cirrus.yml
- .flake8
- test/conftest.py
- test/stress.py
- test/test_timeouts.py
- test/utils.py
Now that we have a lot more Python code, add some project-wide style checking configuration, using flake8.
A couple of easy violations are fixed here, but some that are more difficult are just disabled and might be addressed later (or never).
> Add Python style checks

- src/objects.c
Fixes a bug introduced by #717
Related to #801 (and hopefully fixes)
> Fix calling disconnect_server on a server in BEING_CANCELED state

- src/scram.c
This comes from gcc-12 complaining that a size_t might overflow an int.  Catch it to make the code compile cleanly, but it's not a problem in practice.
closes #790
> Fix obscure compiler warning

- Makefile
We currently make manpages twice, which can fail under concurrency:
```
make[1]: Leaving directory '/build/pgbouncer-1.17.0'
make -C doc
make[1]: Entering directory '/build/pgbouncer-1.17.0'
gcc  -DHAVE_CONFIG_H -Iinclude -Ilib -Wdate-time -D_FORTIFY_SOURCE=2  -g -O2 -fdebug-prefix-map=/build/pgbouncer-1.17.0=. -fstack-protector-strong -Wformat -Werror=format-security -Wall -Wextra -Wno-unused-parameter -Wno-missing-field-initializers -Wmissing-prototypes -Wpointer-arith -Wendif-labels -Wdeclaration-after-statement -Wold-style-definition -Wstrict-prototypes -Wundef -Wformat=2 -Wuninitialized -Wmissing-format-attribute -MD -MP -MT .objs/pgbouncer/lib/usual/tls/tls_ocsp.o -MF .objs/pgbouncer/lib/usual/tls/tls_ocsp.o.d -c -o .objs/pgbouncer/lib/usual/tls/tls_ocsp.o lib/usual/tls/tls_ocsp.c …
```
> Make manpages only once

- doc/config.md
- doc/usage.md
- etc/pgbouncer.ini
- include/bouncer.h
- include/janitor.h
- include/loader.h
- include/objects.h
- src/admin.c
- src/janitor.c
- src/loader.c
- src/main.c
- src/objects.c
- src/proto.c
- src/server.c
- test/test_admin.py
- test/test_peering.py
- test/utils.py
For both performance and availability reasons it can be useful to load
balance across multiple PgBouncer processes, possibly on different
machines. It's very easy to do, by simply putting a generic TCP load
balancer in front of these pgbouncer processes. The `so_reuseport`
option is an example of such a load balancer, which uses the OS kernel
to do the load balancing.
However, there is a problem with this simple approach. Query
cancellations will not work most of the time. The reason is that a
cancellation will open another TCP connection, which might be handled by
another pgbouncer process than the one that is processing the query that
should be cancelled. I talked about this problem in more detail at
the Uptime conference: https://www.youtube.com/watch?v=M585FfbboNA
This change adds …
> Add PgBouncer peering support

- doc/config.md
This was something that was forgotten to add to the docs in #666
> Document the maximum value that can be used for peer_id

- doc/config.md
- etc/pgbouncer.ini
- include/bouncer.h
- src/janitor.c
- src/main.c
Cancellations and regular queries are quite different. So it makes sense
to have different (default) timeouts for cancellation requests than for
queries. While I already think the default query_wait_timeout of 120
seconds we have is excessively long, it doesn't make sense at all to
have such a long timeout by default for cancellation requests that are
not sent. So this introduced a new `cancel_wait_timeout` which is set to
10 seconds by default. If the cancellation request cannot be forwarded
within that time it's probably better to drop it.
One reason why it's important to relatively quickly close cancellation
requests when they are not being handled is because libpq only allows
the client to send a cancel in a blocking way. So there's no possibility
to bail out after a certain amount of …
> Add a dedicated cancel_wait_timeout

- src/pooler.c
When a user requests that a UNIX socket is created and this fails for
some reason we ignored the error. With this change it starts failing
hard when that happens.
This problem is especially bad when so_reuseport is used in combination
with peering, because the peer list would then contain sockets that
don't exist and forwarding cancels would wait for timeout and then fail
silently.
> Fail hard when UNIX socket cannot be created

- src/pooler.c
This fails if listen_addr was specified, but none of the addresses could
be listened on successfully. While not being able to listen on some of
the addresses is often acceptable in practice, not being able to listen
on any of them clearly indicates an error.
This behaviour is the same as how Postgres its behaviour.
Related to #830
> Fail hard if a listen_addr could not be listened on

- src/sbuf.c
PgBouncer is hard to debug when it's trying to connect to Postgres
server over a UNIX socket but that connection fails. You would get an
unhelpful error message like this:
```
WARNING sbuf_connect failed: No such file or directory
```
This change starts including the path in the error message:
```
WARNING sbuf_connect failed to connect to UNIX socket /aaaaa/.s.PGSQL.5432: No such file or directory
```
It also includes the address+port for IPv4/IPv6 connection attempts.
Fixes #835
> Improve warning when connection to unix socket fails

- src/server.c
In most cases the postgres server will not respond anything back to a
cancel message. It simply closes the connection. It won't even report an
error if the cancellation key is incorrect, or the PID is unknown.
However, it is possible that it sends another type of error message,
such as an OOM. Libpq actually ignores those errors and won't show them
to the user, but they might still be sent by the server. Because of the
changes in #717 this could cause a FATAL error. This fixes that by now
handling `SV_ACTIVE_CANCEL` the same as `SV_ACTIVE` in `server_proto`.
Fixes #847
Related to #717, #801, and #815
> Fix FATAL in function server_proto(): server in bad state: 14

- Makefile
This is useful for distro package maintainers, as well as anyone else
that wants to run tests on the published sources.
Fixes #851
> Add files required to run python based tests to release tarball

- .editorconfig
This allows many editors to be configured with correct indentation
styles for the different filetypes that we have. Github also parses this
file and uses it for its web-based editor as well as for displaying
files.
It's a slightly modified version of reverted commit a718ad8. This new
version doesn't specify tab_width and indent_size for C files.
> Retry adding an editorconfig file

- doc/usage.md
What PAUSE waits on depends on the pooling mode, so documenting this command's behavior with respect to running queries is misleading. Instead specify the precise behavior based on the pooling mode.
> Clarify PAUSE docs

- .cirrus.yml
We're now getting this error in CI on every PR:
```
python3 -m pip install -r requirements.txt
error: externally-managed-environment
× This environment is externally managed
╰─> To install Python packages system-wide, try apt install
python3-xyz, where xyz is the package you are trying to
install.
If you wish to install a non-Debian-packaged Python package,
create a virtual environment using python3 -m venv path/to/venv.
Then use path/to/venv/bin/python and path/to/venv/bin/pip. Make
sure you have python3-full installed.
If you wish to install a non-Debian packaged Python application,
it may be easiest to use pipx install xyz, which will manage a
virtual environment for you. Make sure you have pipx installed.
See /usr/share/doc/python3.11/README.venv for more information.
note: If you …
```
> Fix Debian stable setup in CI

- .gitignore
- README.md
- test/README.md
Multiple new contributors had problems running tests locally. I guess
I'm used to Python its objectively bad dependency story, so it wasn't
much of a problem for me. This structures the testing docs a bit better
and also starts linking to them from the README.
It also adds an explanation on how to set up a virtual environment
(which would have solved one problem a contributor had).
> Improve docs on how to run tests

- include/objects.h
- include/proto.h
- include/server.h
- src/admin.c
- src/objects.c
- src/pktbuf.c
- src/proto.c
- src/server.c
PgBouncer currently uses SQLSTATE 08P01 (protocol_violation) as default error code to send error messages to client. There are cases that this SQLSTATE is different from what Postgres provides. Since the goal is to be as transparent as possible, PgBouncer should report the SQLSTATE provided by Postgres. Issue #778 exposes one case that if you connect to a database that doesn't exist, Postgres reports 3D000 (invalid_catalog_name) but PgBouncer reports 08P01. The npgsql driver relies on the SQLSTATE to check if the database already exists and this behavior breaks it. PgBouncer will use the SQLSTATE that Postgres provides.
Fix issue #778.
> Provide SQLSTATE

- src/main.c
- test/conftest.py
- test/utils.py
libpq has been defaulting to prefer for a long time already. Obviously
connecting over TLS is more secure, than without.
The current approach of defaulting to `disable` actually breaks
connecting if your server requires TLS, which many cloud providers are
doing (by default at least).
Fixes #843
> Change default server_tls_sslmode to prefer

- src/pooler.c
I found an odd debug log where it looked like the `src` was trying to contact itself (at a different port); and traced it back with teammates to this location where it looks like the `src` IP is being used twice (though the port is being logged correctly).
> Fix src/dst confusion in log

- Makefile
- include/common/uthash_lowercase.h
- include/varcache.h
- src/varcache.c
- test/test.ini
Override the HASH_FUNCTION and HASH_CMP with case insensitive ones for varcache.
This will enable 
1. The clients to send case insensitive parameters in startup options making it compatible with how postgres handles them.
2. track_extra_parameters values to be case insensitive.
Considered using a list instead, but the use of a hash seemed more advantageous.
- It simplifies creating the initial lookup table handling the duplicate definitions etc.
- It is faster when updating the parameter values.
> Make varcache case insensitive.

- src/admin.c
Closes https://github.com/pgbouncer/pgbouncer/issues/883
> Update `pgbouncer access from unix socket` to respect `log_connections` config option

- doc/config.md
I missed the docs update in #866
> Update docs about new default server_tls_sslmode

- .cirrus.yml
Windows CI has been running out of memory frequently recently. This
changes the test concurrency from 4 to 3 to hopefully reduce memory
pressure a bit.
> Limit concurrency in CI for Windows

- include/bouncer.h
- src/client.c
- src/loader.c
- test/test.ini
- test/test_misc.py
- test/utils.py
It's allowed to specify any Postgres command line parameter in the `options`
startup packet #867. This is commonly used to specify GUC values on connection
startup, using the `-c key=value` command line flag. I believe the main reason
this is used instead of specifying the desired GUC as a startup parameter
directly is because libpq does not allow specifying arbitrary startup
parameters.
This PR adds support for configuring GUCs using the `-c` flag in the options
startup packet. While in theory people can specify any flag they want. In
practice the `-c` flag is the only one that I know is commonly used. Probably
because it is the only one that's documented in the Postgres docs for
`PGOPTIONS`. Any of the other command line flags are simply shorthands for
specific GUCs, and so even when …
> Add support for options startup parameter

- .editorconfig
Let's discuss the indentation rules for C files again. I disagree with the existing text in .editorconfig that basically everybody can do what they want, which seems kind of insane. ;-) The actual rules for pgbouncer source code has always been tab width 8 and indent by tab, so I suggest we put those in here. Note also that the whitespace rules in .gitattributes are set for this.
> Correct editorconfig rules for C files

- .cirrus.yml
FreeBSD 13.1 will EOL in ~2 weeks. This updates CI to use 13.2 instead.
> CI: Update FreeBSD image

- doc/usage.md
- src/main.c
We decided to deprecate online restarts. They have many known problems:
1. It does not work with TLS connections. Most production PgBouncer
setups use TLS connections in some way.
2. `application_name` is not copied over (it's not part of SHOW FDS like
the other tracked GUCs)
3. Any data that's in the `SBuf` its `iobuf` is lost during takeover
(this seems quite bad)
4. It shows this warning during tests right after takover:
```
`WARNING C-0x5620eb57bd90: p1/postgres@127.0.0.1:57066 FIXME: transaction end, but xact_start == 0
```
5. If the config file is different, but has not been loaded yet. Then
many things will almost certainly break.
6. The parameters in `track_extra_parameters` are not copied over to the
new process.
7. It does not work well with SystemD.
The new recommended way to …
> Deprecate online restart

- test/test_admin.py
- test/utils.py
It's a somewhat common operation to want to get the stdout output of a
command that you run. This adds a helper for that and uses it in the
two places that we currently need it.
> Tests: Add a capture helper

- .cirrus.yml
- requirements.txt
We were doing this manually in CI already, but that doesn't help anyone
that wants to run tests themselves on an old python version. This PR
adds contextlib2 to requirements.txt, in a conditional way so that it's
only installed for versions below 3.7.
Fixes #914
> Install contextlib2 for Python 3.6

- doc/config.md
- src/client.c
- test/test_misc.py
By supporting parsing the `options` startup parameter, we accidentally
stopped supporting using it in `ignore_startup_parameters`.
Users have put `options` in `ignore_startup_parameters` and so upgrading
to 1.20.0 might break their existing connection strings, if the actual
options that are contained in the `options` startup parameter are
unsupported.
This changes the parsing of `options` to allow any unsupported parameter
if `options` itself is in `ignore_startup_parameters`.
NOTE: There's other failure paths in the `options` startup parameter
parsing that could still trigger now even though `options` is in
`ignore_startup_parameters`:
- too long parameter
- non `-c` parameter
- options would have been unparsable by PostgreSQL too
But honestly those seem unlikely enough that I think it's …
> Support "options" in ignore_startup_parameters again

- doc/config.md
This was originally reported by @ntse on the repo for the website. And
it was merged in https://github.com/pgbouncer/pgbouncer.github.io/pull/9
During the last release process I noticed that the change was
automatically overwritten, because for `config.md` this repo is the
canonical place. So this does the change again on the right repo.
> Fix confusing typo TLS/TCP typo in docs

- src/util.c
After setting up peering on a PgBouncer setup that had with `log_connections`
and `log_disconnections` enabled I saw some strange logs with empty database
names:
```
2023-08-15 12:51:08.205 CEST [333901] LOG S-0x55a7b1748950: /(nouser)@unix:6432 closing because: successfully sent cancel request (age=0s)
2023-08-15 12:51:08.205 CEST [333901] LOG C-0x55a7b173b300: /(nouser)@127.0.0.1:43772 closing because: successfully sent cancel request (age=0s)
```
This was because the database name for peers databases is all `\0` bytes. This
changes our log prefix callback to include the peerid instead like this for
peer databases:
```
2023-08-15 13:04:52.504 CEST [337755] LOG S-0x555bfbf19950: peer-20@unix:6432 closing because: successfully sent cancel request (age=0s)
2023-08-15 13:04:52.504 CEST …
```
> Fix slog log prefix for peers

- src/util.c
This was missed in #892, because these new lines were added after the
last rebase of that PR (and they did not cause a merge conflict).
> Fix formatting

- test/test_limits.py
On windows CI the test_reserve_pool_size test has started failing pretty
regularly. This increases the sleeps some more to hopefully make it less
flaky. One test I investigated shows that it took ~5 seconds to open the
last of the three reserved pool connections.
```
2023-08-16 09:04:12.876 Greenwich Standard Time [5912] LOG S-00000161ad72a0f0: p1/bouncer@127.0.0.1:10202 new connection to server (from 127.0.0.1:49750)
2023-08-16 09:04:12.963 Greenwich Standard Time [5912] LOG S-00000161ad72a330: p1/bouncer@127.0.0.1:10202 new connection to server (from 127.0.0.1:49751)
2023-08-16 09:04:13.006 Greenwich Standard Time [5912] LOG S-00000161ad72a570: p1/bouncer@127.0.0.1:10202 new connection to server (from 127.0.0.1:49752)
2023-08-16 09:04:13.060 Greenwich Standard Time [5912] LOG …
```
> Increase sleeps in test_reserve_pool_size to avoid flakyness

- test/test_limits.py
- test/test_timeouts.py
In 1.20.0 we started using `server_tls_sslmode=prefer` by default. This
sets it to `disable` for specific tests that depend heavily on specific
timings. These timings would be messed up on some OSes in CI, because
now PgBouncer would first try to connect using TLS and when that failed
it would try connect without. Especially on Windows CI a failed TLS
connection to localhost seems to sometimes take significant time.
> Use server_tls_sslmode=disable in some flaky tests

- src/client.c
- src/objects.c
The cancel request protocol is very simple:
1. Clients send a cancel key
2. Server cancels the query running on the matching backend
3. The server closes the socket to indicate the cancel request was
handled
At no point after sending the cancel key the client is required to send
any data, and if it does it won't get a response anyway because the
server would close the connection. So most clients don't, specifically
all libpq based client don't.
The Go client however, sends a Terminate ('X') packet before closing the
cancel socket from its own side (usually due to a 10 second timeout).
This would cause a crash in PgBouncer, because PgBouncer would still
listen on the client socket, but on receiving any data we wouldreport a
fatal error. This PR fixes that fatal error by stopping to listen …
> Fix FATAL in function client_proto(): bad client state: 6/7

- src/server.c
Fixes #822
Related to #904 and #717
In #904 @tnt-dev reported to still get the issue in #822 on 1.19.1 (on
which it was expected to be fixed).
```
2023-08-12T16:34:07+00:00 pgbouncer[4920]: @src/server.c:591 in function server_proto(): server_proto: server in bad state: 11
2023-08-12T16:34:07+00:00 systemd[1]: pgbouncer.service: Main process exited, code=exited, status=1/FAILURE
2023-08-12T16:34:07+00:00 systemd[1]: pgbouncer.service: Failed with result 'exit-code'.
2023-08-12T16:34:07+00:00 systemd[1]: pgbouncer.service: Consumed 1h 51min 3.308s CPU time.
2023-08-12T16:34:07+00:00 pgbouncer[4920]: @src/server.c:591 in function server_proto(): server_proto: server in bad state: 11
2023-08-12T16:34:07+00:00 pgbouncer[4920]: started sending cancel request
```
Looking again, I now understand …
> Fix FATAL in function server_proto(): server in bad state: 11

- .flake8
- pyproject.toml
Discovering tests and running linters takes longer than necessary,
because they traversed the submodules. This excludes them everywhere.
> Exclude lib and uthash directory for python tooling

- Makefile
This makes stacktraces triggered by pytest-timeout easier to read,
because there's only a single process running instead of two. This
especially impacts Windows.
> tests: Don't use pytest-xdist if no concurrency is requested

- include/objects.h
- src/admin.c
- src/client.c
- src/objects.c
- test/conftest.py
- test/test_auth.py
When the database section has an auto-database, '*', the expected behavior for login experience to have client's database registered when not found. However, this experience would be blocked if we configure `auth_dbname` to fall to auto-database. Hence, the main goal of this PR is to ensure that `auth_dbname` can still function on cases where it is not configured, but auto-database is provided.
To achieve that, this PR makes already existing function, find_or_register_database, public and uses it from various places to simplify code.
Edit:
Quoting the targeted use case of this change from @JelteF 's comment, which makes the change more presentable:
```ini
[databases]
* = host=localhost
[pgbouncer]
auth_dbname=postgres
```
Where, we will use `auth_dbname=postgres` with auto-registered …
> [auth_dbname] introduce auto-registration option in case auto-database is configured

- .cirrus.yml
- README.md
- configure.ac
- doc/config.md
- src/dnslookup.c
libudns is not maintained for a long time (+9 years) [1]. Since there are other DNS resolvers that have been maintained and there isn't a modern operating system that enables it, remove libudns support.
[1] https://www.corpit.ru/mjt/udns.html
> Remove udns

- .cirrus.yml
Ubuntu 18.04 has been causing build issues in PR #845, because we
started using a unicode symbol in the docs. This fails the docs build.
Since Ubuntu 18.04 has been EOL since April, it seems better to drop
support than to add code to work around this.
PG9.6 is also EOL, but continuing to support it hasn't been a big issue
yet. Also it seems useful for PgBouncer to still be able to talk to EOL
Postgres instances, but running the newest version of PgBouncer itself
on EOL operating systems seems much less useful.
We still remove the whole matrix task though, because there's already
another task with PG9.6.
> Stop supporting Ubuntu 18.04, since it is EOL

- .cirrus.yml
Cirrus is limiting free usage of its CI more to combat misuse for crypto
mining: https://cirrus-ci.org/blog/2023/07/17/limiting-free-usage-of-cirrus-ci/
This reduces the amount of jobs that we run to hopefully get CI to run
reasonably fast again.
> Reduce CI builds because of lowered Cirrus credits

- src/admin.c
- src/proto.c
- src/scram.c
A static analyzer found some errors -
1) Deref of Null - admin.c
>Return value of a function 'pktbuf_dynamic' is dereferenced at admin.c:245 without checking for NULL, but it is usually checked for this function (25/26).
2) Memory Leak - proto.c
>Dynamic memory, referenced by 'ibuf', is allocated at proto.c:474 by calling function 'malloc' and lost at proto.c:488.
3) Memory Leak - scram.c
>Dynamic memory, referenced by 'server_signature_base64', is allocated at scram.c:932 by calling function 'malloc' and lost at scram.c:938.
4) No VA End - proto.c : 686; 
>Function 'va_end' was not called before proto.c:686 inside function 'scan_text_result'. (Function 'va_start' was called at proto.c:624.)
5) No VA End - proto.c : 693
>Function 'va_end' was not called before proto.c:693 inside function …
> Fix errors pointed out by static analyzer

- include/util.h
- src/client.c
- src/proto.c
- src/util.c
- test/Makefile
Root cause:
MD5 encryption functions are internally implemented in libusual (./lib/usual/crypto/md5.c). MD5 Authentication functions can not be used on FIPS compliant host. Due to internal implementation of MD5 algorithm, MD5 authentication is working without error on FIPS enabled host. Ideally it should throw error.
Solution:
Due to internal implementation, we are not using openssl APIs for MD5. In this fix all internal MD5 calls are replaced to openssl APIs after which MD5 authentication throws expected error on FIPS compliant host.
Testing:
Pytest  testsuite ran successfully.
MD5 authentication scenario on non-FIPS compliant host runs successfully with and without compiling with “--without-openssl ” flag.
MD5 authentication scenario on FIPS compliant host errors out as expected when …
> PgBouncer md5 FIPS compatibility changes

- src/server.c
If the server connection returns a FATAL error in the login phase we
kill all the waiting clients and show this error to the user. The reason
is that when this happens it's usually because of some configuration
error (e.g. pg_hba.conf on Postgres not being configured correctly).
But there are common cases where the error is temporary too, most
importantly: "the database system is starting up"
Postgres returns a specific error code for these types of errors. This
PR starts checking for that error code, and won't disconnect the clients
when it received a FATAL error from the server with that specific error
code.
The primary reason I spent time to fix this is because it was making
our tests flaky:
https://cirrus-ci.com/task/5607330616705024
> Don't kill all waiting clients on temporary FATAL errors during login

- doc/config.md
- src/objects.c
- src/proto.c
We were using the full 64 bits of the BackendKeyData message as random
bytes. This turned out to be arguably incorrect, because the first 32
bits are used by PostgreSQL as a Process ID (and this is part of the
[protocol documentation too][1]). Actual PIDs are always positive, but
we also put a random bit in the sign bit so were setting it to negative
numbers half of the time. For most cases this does not matter, but it
turned out that [`pg_basebackup` relied on the PID part to actually be
positive][2].
While `pg_basebackup` is now fixed to support negative Process IDs, it
still seems good to adhere to this implicit requirement on positive
numbers in case other clients also depend on it.
Since this change requires changing the bytes of the cancel key in which
we encode the `peer_id`, this …
> Only use positive numbers in the PID part of the cancel key

- pyproject.toml
- test/test_auth.py
- test/test_no_database.py
After c74d1cd, the test suite will not pass if OpenSSL is in FIPS mode.  To allow the test suite to pass anyway, mark affected tests with the "md5" pytest marker.  That way, these tests can be skipped, e.g., with `pytest -m 'not md5'`.
---
Further thoughts:
* [Here](https://www.postgresql.org/message-id/c8f11f3c-c267-1f62-f90c-619b8fae9013%40enterprisedb.com) is an analogous discussion for core PostgreSQL. There, the proposed patch checks first if the `md5()` function works. We don't have such an option for PgBouncer, I think, hence the manual toggle.
* We could also do an environment-variable based skip, like for sudo, but I think the marker approach is more native to pytest.
* Some of these tests could probably be rewritten to not use md5 (use scram instead), since they are not really …
> Allow tests to pass in FIPS mode

- doc/config.md
We removed support for UDNS, but it was still referenced in one part of
the docs.
> Remove final mention of UDNS

- doc/config.md
- src/server.c
- test/test_prepared.py
This implements a hacky/clever approach of handling the `DEALLOCATE ALL` and `DISCARD ALL` SQL statements. Instead of parsing the queries themselves, which PgBouncer avoids doing completely, this parses the CommandComplete packet returned by the server.
Fixes https://github.com/prisma/prisma/issues/21635
Fixes #974
> Handle DEALLOCATE ALL and DISCARD ALL for prepared statements

- doc/config.md
- include/bouncer.h
- src/client.c
- src/janitor.c
- src/loader.c
- test/README.md
- test/test_auth.py
This adds support for allowing specifing a different auth_query for different databases. This is useful if the auth_query needs to contain an encryption key that can differ per database.
Fixes #910
> Support configuring auth_query per database

- doc/config.md
I was curious about this as a new user, and couldn't find any documentation on how prepared statements are cached. Looked into the source code (https://github.com/pgbouncer/pgbouncer/blob/6c7730e2e9f2a5710292a5535e17dbb8882679ff/src/prepare.c#L230) and it appears a Least Recently Used (LRU) cache is used. This is useful information for users.
> DOC: Prepared Statements: mention LRU Cache

- src/main.c
- test/test_auth.py
To make `valgrind` pass we have a cleanup function that we only use in
assert mode. In this function we free all globals before process exit.
However, we didn't free `parsed_hba`. This fixes that. In passing it
also slightly modifies how we free `parsed_hba` when reloading the
config.
Fixes #1000
> Fix false positive reported by valgrind when using hba

- include/varcache.h
- src/server.c
- src/varcache.c
- test/test_misc.py
Since PG14, Postgres doesn't send ParameterStatus packets anymore when a
setting has not actually changed. This could cause the client varcache
and server varcache to become out of sync. Which then in turn resulted
in unnecessary `SET` commands to be sent to the server.
Fixes #776
> Update client varcache with canonical values from server

- src/varcache.c
- test/test_misc.py
It was reported in #993 that using an empty `application_name` on
connection startup could result in the actual `application_name` that was
set later not being detected. The reason was that we were explicitely
not forwarding empty strings from clients as settings to Postgres. This
is fixed by simply removing this check. Why we were explicitely ignoring
empty strings is not clear to me. One possible reason is because when
this code was introduced, the empty string was an invalid value for
all of the supported startup parameters. But our handling of startup
parameters and GUCs has heavily changed over the years, and is
able to handle them fine like this and the empty string is a valid
value for `application_name`.
Fixes #993
> Fix handling of empty application_name

- doc/config.md
Add documentation in section databases about `auth_dbname` option to override global setting.
> docs: add auth_dbname in section databases

- test/utils.py
This can make debugging test failures a lot easier, since the test
output now contains NOTICE and WARNING messages.
> Add a NOTICE handler to test runner

- src/server.c
- test/test.ini
- test/test_auth.py
- test/test_no_database.py
- test/utils.py
For a very long time, we've had logic to quickly close all clients when
the a server could not be connected to.
This wasn't working correctly in all cases, one of those was when an
`auth_user` was set (and no `auth_db`). This was reported in #989.
While looking closer into that issue I realized it also wouldn't handle
cases where first connecting worked but then after a while it doesn't
anymore, because it relied only on `wait_for_welcome`. It's not strictly
necessary to kill all waiting connections when creating new server
connections is not possible anymore, as long as there are still working
server connections. But if those don't exist either, then we're
effectively in the same state as complete refresh (except that we have
cached the welcome message).
Fixes #989
Fixes #985
> Improve connection fail fast logic

- .cirrus.yml
- src/sbuf.c
- test/hba_test.rules
- test/test_ssl.py
Windows CI was broken due to two things:
1. Static linking to OpenSSL causes `./configure` to fail
2. The `test_hba_leak` test was failing
This fixes these issues, but SSL tests are now broken on Windows.
Fixing that is left for a future PR by disabling SSL tests for for now.
This way we at least don't introduce other breakages in the mean
time (like number 2).
> Unbreak windows CI

- .editorconfig
Our hba_test.eval and hba_test.rules file only look well aligned with 8
size tabs. This configures editors (and GitHub) to display them as such.
> Add editorconfig rules for our hba_test files

- include/bouncer.h
- include/objects.h
- src/client.c
- src/objects.c
- src/server.c
- test/Makefile
- test/conftest.py
- test/test_copy.py
- test/utils.py
In #845 full tracking of expected responses was implemented. This turned out to have bugs when sending `COPY FROM STDIN` queries using the extended protocol. [The protocol explicitly allows sending `Sync` messages after sending an `Execute` message for a `COPY FROM STDIN` command][1]. Such Sync messages are ignored by the server until a CopyDone or CopyFail message is received. The new command queue tracking did not take this into account, and was incorrectly expecting more ReadyForQuery messages from the server.
This could lead to two problems for the server connection on which the `COPY FROM STDIN` was sent:
1. The server connection would never be unassigned from the client.
2. Memory usage for this server connection would continue to increase until the client disconnects.
3. If …
> Fix COPY FROM STDIN handling

- .cirrus.yml
- test/test_ssl.py
Builds have started failing since the previous images don't exist
anymore. Also disables SSL tests on OSX for now, because these
seem to be broken for some reason on the new images. Fixing
those tests is considered out of scope for this PR, but it is
tracked in #1031 (because it should be fixed).
> Update FreeBSD and OSX images for CI

- doc/config.md
- etc/pgbouncer.ini
- include/hba.h
- src/client.c
- src/hba.c
- src/main.c
- test/hba_test.c
- test/pgbouncer_hba.conf
- test/pgident.conf
- test/ssl/create_certs.sh
- test/test_auth.py
Postgres supports user name maps[1] for `cert`  and `peer` authentication methods. This change provides the same functionality with some limitations for pgbouncer. The limitations are listed in "Ident map file format" section of the docs.
1. https://www.postgresql.org/docs/current/auth-username-maps.html
Fixes #767
Fixes #148
> Introduce auth_ident_file setting and enhance cert and peer auth methods with user name maps

- include/bouncer.h
This clarifies why we have waiting_cancel_req_list in addition to
waiting_client_list.
> Expand code comment on waiting_cancel_req_list

- doc/usage.md
- src/admin.c
While reviewing #1039 I had a hard time seeing if
max_user_connections was applied correctly because `SHOW USERS` didn't
list it. This addresses that by adding a `max_user_connections` and
`current_connections` column to the output of `SHOW USERS`.
> Change SHOW USERS to list connections

- src/client.c
I realized I was a bit too trigger-happy when removing all references to
`expected_rfq_count` in #1025. One occurrence should have been replaced
with adding an outstanding request. Normally this isn't an issue, but it
could cause the server connection not to be closed if the client
disconnects before the auth_query is finished running.
To be clear, #1025 did not introduce a regression in this respect.
Because `expect_rfq_count` being non-zero on would not cause
a server connection closure when the server was released.
> Add outstanding request for auth_query

- src/dnslookup.c
The newest version of c-ares has started adding deprecation warnings.
Let's silence those for now to make MacOS builds pass again.
We might want to actually start using the new APIs in the future, but
since we want to support some fairly old systems I'm not sure that's a
good plan now. And given [the library author stated that the old
functions would probably never be removed][1], I think we're fine with
simply ignoring the warnings.
[1]: https://github.com/c-ares/c-ares/pull/732#issuecomment-2028454381
> Silence deprecation warnings of c-ares

- test/utils.py
This fixes an issue that I ran into where
`test_equivalent_startup_param` failed on my new laptop because initdb
would use `'iso, dmy'` as datestyle instead of `'iso, mdy'`.
> Fix tests on non US datestyle configured systems

- doc/config.md
- doc/usage.md
- etc/pgbouncer.ini
- include/bouncer.h
- src/admin.c
- src/loader.c
- src/objects.c
- src/server.c
- test/conftest.py
- test/test.ini
- test/test_limits.py
- test/userlist.txt
Specifying `pool_size` is now possible in section `[users]` beside `[databases]` or as a global param. Possibility of specifying `pool_size` in user configuration was requested in the associated issue. Resolves #911.
Looking forward to discussing the implementation details or the issue ratioinale if needed.
Thanks,
Michal
Note: This is my first pull request for this project. I picked this issue as it was labeled as 'good-first-issue' and I wanted to get acquainted with the project.
> Allow pool_size per user

- include/proto.h
- src/client.c
- test/test_misc.py
- test/test_prepared.py
- test/utils.py
We were bailing out from a connection if we did not receive the full
startup packet in one go, or if it didn't fit in pkt_buf. This fixes
these issues by reusing the packet buffering logic that was introduced
for prepared statement support for our startup packet parsing.
Fixes #1056
> Correctly handle large and partial startup packets

- include/bouncer.h
- include/pktbuf.h
- src/client.c
- src/pktbuf.c
- src/proto.c
PgBouncer currently only supports protocol version 3.0. However, it was
still accepting connections if the client asked for the 3.1 protocol
version. This is obviously a bug, because PgBouncer likely won't
support the changes introduced in 3.1 of the protocol without
any code changes.
This starts sending the NegotiateProtocolVersion message when the client
asks for a minor version that PgBouncer does not support. Also, instead
of erroring when it receives unsupported protocol extensions parameters
it will include these in this NegotiateProtocolVersion message.
For reference this is the Postgres commit introducing NegotiateProtocolVersion: https://github.com/postgres/postgres/commit/ae65f6066dc3d19a55f4fdcd3b30003c5ad8dbed
I tested this manually using this patchset that bumps the protocol …
> Add support for negotiating the protocol version with the client

- doc/usage.md
- include/bouncer.h
- include/pooler.h
- src/admin.c
- src/janitor.c
- src/main.c
- src/objects.c
- src/pooler.c
- test/test_misc.py
- test/test_peering.py
- test/utils.py
In 1.20 we announced deprecation of online restarts using the `-R` flag and recommended for people to use `so_reuseport` instead. But the safe shutdown logic that we executed when receiving a `SIGINT` signal didn't actually allow for zero-downtime rolling restarts.
This PR changes the behaviour of our shutdown signals to allow for rolling restarts. The changes that this PR makes are:
1. SIGTERM does not do "immediate shutdown" anymore, but instead triggers a newly introduced "super safe shutdown". This "super safe shutdown" waits for all clients to disconnect before shutting down the server. This can be used for rolling restarts as described in the newly added documentation. A second SIGTERM will cause an "immediate shutdown".
2. SIGINT mostly keeps doing what it was doing previously: …
> Redesign shutdown logic to support rolling restarts using so_reuseport

- src/client.c
- test/test_misc.py
The `-c config=value` pattern has been supported in PgBouncer since
PR #878. As described in #952 Postgres also allows to use the
`--config=value`, which honestly seems more readable, but for some
reason is mentioned almost nowhere in the Postgres documentation.
Since #878 this always throws an error, and putting `options` in
`ignore_startup_parameters` wouldn't get rid of this error. So this
should actually be considered a regression for the same reason as #907
was considered a regression (although a much less impactful one given
we've only received two reports of this causing issues).
Fixes #952
> Support --config=value format in options startup parameter

- src/hba.c
The 1st argument of calloc is the number of elements of the array that we want to allocate space for[^1].  This patch is trying to pgbouncer's CI happy.
[^1]: https://man7.org/linux/man-pages/man3/calloc.3p.html
> The 1st argument of calloc should be 'nelem'.

- .cirrus.yml
Reactive some tasks that were commented out in 92b4645.  Instead, set them to trigger manually.  That way, they can still be used individually when desired.
> Reactivate some Cirrus CI tasks with manual trigger

- doc/config.md
- include/hba.h
- src/hba.c
- test/hba_test.c
- test/hba_test.eval
- test/hba_test.rules
This change adds support for "all" address type in HBA file that matches both 0.0.0.0/0 and ::/0, similar to PostgreSQL HBA.
https://postgresql.org/docs/16/auth-pg-hba-conf.html#:~:text=You%20can%20also%20write%20all%20to%20match%20any%20IP%20address
> Add support for "all" address type in HBA file

- doc/config.md
Improving documentation on connecting to AWS RDS that uses SCRAM authentication.
Some managed servers such as AWS RDS for PostgreSQL restrict access to `pg_authid` (`pg_shadow`) which makes configuration of authentication between PgBouncer and backend server somewhat difficult. Configuring SCRAM for both PgBouncer and backend server has been clearly a pain point for some PgBouncer users who experienced connection problems related to failing authentication (see #787, #981). 
Therefore a better documentation could help clarify these restrictions and prevent some of these issues. Introduced two new sub-chapters: 
one for existing limitations regarding using SCRAM authentication for PgBouncer
and one for restrictions of managed servers (AWS RDS).
Feedback is welcome (especially on clarity of …
> Improve documentation on connecting to AWS RDS and SCRAM

- etc/pgbouncer.service
In production environments most people will want PgBouncer to
automatically restart if it crashes for some reason. This changes our
systemd template file to do that.
As suggested by @phemmer in https://github.com/pgbouncer/pgbouncer/issues/314#issuecomment-2129664358
> Change systemd service file to automatically restart PgBouncer

- test/test_admin.py
- test/test_replication.py
- test/utils.py
This improves the ergonomics of the `run` helper function in our test suit. It now autodetects if `shell=True` or `shell=False` should be passed based on the type of the first argument. It also automatically converts arguments to string in case a list is passed.
> Improve run python function

- src/client.c
start_auth_query does not check that get_pool returned NOT NULL pointer.
As result, find_server (in the next call) may get AV.
See #1107 for details.
> Fix for #1107

- include/objects.h
- src/janitor.c
- src/objects.c
- test/test_misc.py
After the refactoring of the user managament in #1052, we incorrectly freed credentials by calling `slab_free` on a user_cache, instead of `credentials_cache` in two places. This could later cause segfaults because ththe user type is larger than the credentials type, so out of bound reads would be possible when the credential that was put into the user_cache was taken out again and used as a user instead.
> Fix for #1104 [free PgCredentials]

- test/Makefile
These two files are required by regression tests since 1.23.0 but haven't been packed into tarball during make dist. This commit fixes this problem.
> Add files pgbouncer_hba.conf and pgident.conf to tarball

- include/bouncer.h
- src/objects.c
- test/conftest.py
- test/test_auth.py
For a long time we've had issues where users with the same named in the
config would cause strange "put_in_order" errors. These errors happened
in even more cases following the user management refactor that was done
in #1052. Luckily this same user management refactor made fixing the
root-cause very easy: By moving the pool_list to the global user struct
from the credential struct we now ensure that a single pool is only
added once.
Fixes #1116
Fixes #1103
Fixes #502
Resolves #1117
Resolves #1106
Related to #817
Related to #1052
> Fix all known put_in_order crashes

- test/utils.py
On certain test environments, there can be unconfigurable hosts where IPv6 takes precedence over IPv4 (normally, one could control that through /etc/gai.conf, but if the environment is restricted, it is not possible.) This leads PgBouncer to PostgreSQL connections to be opened in IPv6 traffic, where PostgreSQL doesn't accept such communication since it is not configured to do so. Eventually, the test times out. As an example:
```
#18 231.3 ____________________________ test_client_ssl_scram _____________________________
#18 231.3 [gw0] linux -- Python 3.9.19 /usr/bin/python3
#18 231.3 /orcasql-pgbouncer/test/test_ssl.py:330: in test_client_ssl_scram
#18 231.3     bouncer.psql_test(
#18 231.3         bouncer    = <test.utils.Bouncer object at 0x7f76a7a89070>
#18 231.3         cert       = …
```
> Make PostgreSQL listen on both IPv4 and IPv6 during tests if IPv6 interface is supported

- doc/config.md
This PR cleans up some instances of trailing whitespace in config.md. Minor issue but some confusion can arise as many people configure their code editors to remove trailing whitespace from markdown files on save.
> Cleanup trailing whitespace

- doc/config.md
Hey @JelteF, today I was looking to crank the log verbosity up to hopefully diagnose a vexing issue and had to look at the source to learn that setting it to anything higher than 2 would be useless.
Cheers
> Document current maximum verbosity config value

- src/hba.c
This PR fixes different problems in function parse_ident_line (hba.c).
1. This function did not check strdup results
2. This function could return by error without cleanup
3. This function did not free map_name_copy in 'failed' section
Additional DEBUG checks:
1. 'failed' section cannot get a not null value of ident_map. I suggest to remove "ident_map_free(ident_map);" from there.
> Fix for #1100 [parse_ident_line (hba.c)]

- src/objects.c
objects_cleanup resets user_tree but not do it for pam_user_tree.
> reset pam_user_tree in objects_cleanup

- src/objects.c
Hello,
It is a small proposal for improvements code to avoid any questions and problems in the future.
user_tree stores PgGlobalUser objects but uses credentials_node_cmp that oriented on PgCredentials.
Of course, it works because PgGlobalUser::credentials is a first member of PgGlobalUser.
To avoid any problems in the future, I offer to define and use exact compare function  for PgGlobalUser::credentials::tree_node - global_user_node_cmp.
Thanks.
> Exact compare function for PgGlobalUser::credentials::tree_node

- include/util.h
- src/loader.c
- src/util.c
- test/hba_test.c
In the lib it was renamed strings_equal => strcmpeq for naming consistency within libusual
https://github.com/libusual/libusual/pull/57
> Move string checking utility to libusual

- src/loader.c
This PR fixes memory leaks in parse_database and parse_peer functions.
See #1098 for details.
> Fix for #1098 [memory leaks]

- doc/config.md
- src/main.c
- test/test_prepared.py
By the time we'll release the next PgBouncer version it will be roughly
a year since we added prepared statement support as an opt-in feature.
Quite a few managed services enabled this feature by default. Only very
few issues were reported that were related to it, and all of them have
been fixed.
Since defaults matter, I think it's time that we change the default to
enable this feature by default in the next release. I'd like to merge
this early in the release cycle so that devs have the highest chance of
finding any more issues with it. But I expect no new issues to be found.
> Enable prepared statement support by default

- .gitignore
This PR adds \_\_pycache\_\_ to pgbouncers .gitignore file. This file is created when running pytest and needs to be manually excluded from commits/PR's. 
Just for some external backup: see the link below  for Githubs recommendations for  python .gitignore files, they incude \_\_pycache\_\_ in this file.
https://github.com/github/gitignore/blob/main/Python.gitignore
> Add pycache to .gitignore

- README.md
- etc/pgbouncer.service
- src/main.c
This PR adds support for using pgbouncer with `Type=notify-reload` systemd service.
See https://www.freedesktop.org/software/systemd/man/latest/sd_notify.html
Note that `Type=notify-reload` services do not need `ExecReload=` command and use `ReloadSignal=` that conveniently defaults to SIGHUP.
> Add support for Type=notify-reload with systemd

- doc/usage.md
- include/admin.h
- src/admin.c
- test/test_admin.py
This PR adds a kill_client command to the admin console. This command is the equivalent of the Postgres pg_terminate_backend() function. Similar functionality also exists in other Postgres connection poolers.
In general this functionality is a useful last resort to undisciplined users opening a lot of connections and which block out other users. This is especially prominent with front end GUI DB applications that open a new session for every SQL editor tab.
> Add kill_client command

- src/main.c
Closes https://github.com/pgbouncer/pgbouncer/issues/1174
> Separate error handling for empty pidfile

- include/client.h
- src/client.c
- src/objects.c
- src/proto.c
- test/test_replication.py
The way we send an auth_query is a bit strange. We temporarily set the
pool of the client to the pool for the auth_user, and then continue
connection startup like normal. This broke for replication connections
because we would send the replication parameter for that connection too.
This fixes that by only doing our special connection setup logic for
replication connections if we're not currently trying to send an
auth_query.
Fixes #1164
> Handle auth_query correctly for replication connections

- .cirrus.yml
This looks like it is solving the error that has been occurring in the recent Windows CI runs.
For reference, the errors are of this form:
```
C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>call sh -l -c "./autogen.sh" 
Using autoconf: 2.72
Using aclocal: 1.17
ac-wrapper: autoheader: warning: auto-detected versions not found ( ); falling back to latest available
ac-wrapper: autoconf: warning: auto-detected versions not found ( ); falling back to latest available
configure.ac:15: warning: The macro 'AC_PROG_CC_STDC' is obsolete.
configure.ac:15: You should run autoupdate.
../autoconf-2.72/lib/autoconf/c.m4:1669: AC_PROG_CC_STDC is expanded from...
lib/m4/usual.m4:69: AC_USUAL_PROGRAM_CHECK is expanded from...
configure.ac:15: the top level
configure.ac:17: error: …
```
> Install pkg-config in Windows CI

- test/test_auth.py
The new error message test introduced by #1152 is failing on Windows.
This slipped past CI, because Windows CI was broken completely
before #1216.
For now this disables the test on Windows to make CI green, but it might
be nice to actually fix the behaviour.
> Disable error message test on Windows

- doc/config.md
- src/client.c
- src/hba.c
Cursory code review has shown no reason why "pam" should not be
supported in pg_hba.
Add "pam" to the list of supported authentication methods in
the HBA file - only if generally available, of course - and
edit docs to match the new reality.
Fixes #501
> Enable "pam" authentication support via HBA

- test/ssl/newca.sh
- test/test_ssl.py
It appears that recent versions of the OpenSSL library require the "Basic Constraints" X509 extension to be properly configured for CA certificates. The x509v3_config(5) man page states:
"A CA certificate must include the basicConstraints name with the CA parameter set to TRUE. An end-user certificate must either have CA:FALSE or omit the extension entirely."
Currently, the basic constraints are not set when generating CA certificates and SSL tests fail on distros with new OpenSSL libraries such as Rocky Linux 9. This PR fixes the issue.
For reference: https://docs.openssl.org/3.4/man5/x509v3_config/#basic-constraints
Fixes #1210 
Fixes #1031
> Set Basic Constraints X.509 v3 extension

- test/ssl/newca.sh
The `-addext` option was introduced in OpenSSL 1.1.1. We need to skip it to support old OpenSSL versions (1.0.x).
See also #1210
> Skip -addext option for OpenSSL 1.0.x

- NEWS.md
- configure.ac
I noticed that in the most recent build the version number still displays as v1.23.0. I believe that the below number should have been incremented with the last update.
> Fix version  in configure.ac

- src/objects.c
- test/test_limits.py
Fix for [#1225](https://github.com/pgbouncer/pgbouncer/issues/1225). 
It seems that sometimes when a connection is closed pgbouncer does not make a call to `disconnect_client`. Instead it goes through `disconnect_client_sqlstate`. This PR moves the count decrementing from `disconnect_client` and to `disconnect_client_sqlstate` so that it gets counted more often.
Added a test case that proves this out which fails when running against the current state of pgbouncer.
> Fix Client Connection Count Decrementing

- src/janitor.c
- src/objects.c
This PR implements the non default option of choosing zero as the default pool size and not having the restriction apply. This is useful in situations where you would rather limit connections by user or database instead of pool. Without this option it can be easy to forget to make sure that default pool size is larger than the limit you actually want to apply.
> option to disable default pool size

- src/admin.c
A previous version of kill_client used ptr. This is no longer the case. Updating help to reflect this change.
> Fix kill_client help

- doc/config.md
- doc/usage.md
- etc/pgbouncer.ini
- src/admin.c
- src/loader.c
- test/test.ini
- test/test_limits.py
Based on discussion here: https://github.com/pgbouncer/pgbouncer/pull/1228
Updating the database parameter name from `reserve_pool` to `reserve_pool_size` to be consistent with everything else. 
Do you prefer to advertise the deprecation through the release notes only or also make a note in the parameter's documentation?
> Change db param to reserve_pool_size

- requirements.txt
This PR attempts to fix CI by pinning the psycopg version. This will make it  a manual process to upgrade psycopg but at least it will not cause CI failures on the master branch anytime psycopg does a release that changes its behaviour in unit tests.
> Pin psycopg version

- requirements.txt
- test/test_misc.py
- test/test_timeouts.py
These failures were previously addressed by @AndrewJackson2020
in #1249 by pinning psycopg to 3.2.3. I became aware of this because I
just re-enabled the python test suite in Debian[1] [2].
This is a good change in psycopg[3]. Let's update the assertions and bump
the version.
Open question around whether or not we should pin here? It would be good if
we can sort these issues out before they block the upload of new
pgbouncer packages to downstream distros (although most folks probably
care more about pgdg?) No worries either way.
[1]: https://www.postgresql.org/message-id/CAOMoQbROhu7WG9LnyjHb1RXJrax_HKKMBbwaou%2Bjps0uZgqHFw%40mail.gmail.com
[2]: https://www.postgresql.org/message-id/CAGKCzNAQKMKJ_BQcF%3DuzcfcM%3Dvx8QYnT%2Bjtzuv_yp%3D76zbhn7g%40mail.gmail.com
[3]: …
> Fix assertion failures introduced by psycopg 3.2.4

- test/test_prepared.py
Although Debian proper does not release PG/libpq=17 for bullseye
(oldstable) the PostgreSQL Debian team does release those packages for
bullseye via "pgdq".
Unfortunately, `psycopg` adds `Close` support in version 3.2.0 and it
would be a much _bigger_ lift to support that package[1].
This leaves a tiny gap in our integration testing for bullseye but I
think we can be confident that pgdg users will be able to
`close_prepared`.
Debian Trixie becomes Debian `stable` in a few months, and so this will
be moot for OSS packagers when bullseye moves to `oldoldstable` but I
and other users have an interest in being able to use the latest
pgbouncer while migrating to Debian stable.
[1]: https://www.postgresql.org/message-id/Z6Is1o56psB3-TMT%40msg.df7cb.de
> Skip tests for Close messages on Debian oldstable

- doc/config.md
The videos from the Uptime conference were sadly all removed it seems. Luckily I gave this talk at another conference too where it was recorded.
Fixes #1270
Related to #1276
> Use new cancel video link

- test/ssl/newca.sh
Hello! Сommit #1221 introduced new changes needed to ensure that on systems with old openssl (v1.0.x) certificates are generated correctly by skipping the -addext option. But I found out that on the astra-leningrad-8.1 system, on which the openssl 1.1.f version, the check proposed in the above-mentioned commit will not work. I suggest adding a check for the second digit in the version number.
Examples:
```
test@astrassd:~/test/pgbouncer-1.24.0$ openssl_version=`openssl version | awk '{print $2}'`
test@astrassd:~/test/pgbouncer-1.24.0$ echo $openssl_version
1.1.0f
test@astrassd:~/test/pgbouncer-1.24.0$ expr "X$openssl_version" : 'X1.0.*'
0
test@astrassd:~/test/pgbouncer-1.24.0$ expr "X$openssl_version" : 'X1.*.*'
7
```
Test without patch:
```
test@astrassd:~/test/pgbouncer-1.24.0$ pytest …
```
> Also check the second digit in the openssl version when creating certificates

- test/utils.py
C-strings are `NULL` terminated and so `MAX_PASSWORD_LENGTH` =
`MAX_PASSWORD - 1`.
Additionally, the regex matcher for pulling out `MAX_PASSWORD` was wrong
and only got "2" when it should have been "2048".
This closes #1268
> Fixup longpass auth tests

- doc/config.md
- src/client.c
- src/hba.c
This reverts commit f856951fa6d7fc670e74b1dfeb301fcb949c3caf.
As reported in #1261 this broke PAM authentication completely, so I'm
reverting this. I won't be touching PAM code anymore until someone adds
some automated tests.
Fixes #1261
> Revert "Enable "pam" authentication support via HBA (#326)"

- include/server.h
clang-tidy identified a minor naming inconsistency between parameter naming in server.h/server.c
https://clang.llvm.org/extra/clang-tidy/checks/readability/inconsistent-declaration-parameter-name.html
> fix clang readability warning (inconsistent declarataion parameter name)

- src/common/saslprep.c
Doing a bit of testing in AWS I discovered that the token (which is over 1024 bytes) would cause pg_bouncer to segfault when the server requests SASL auth. With some digging I found that the MAX_PASSWORD_LENGTH in `saslprep.c` didn't match what was defined in bouncer.h. 
This small patch just ensures the value matches. There is probably a better way to have this defined in one place instead of two. Alas this is a quick fix for those who may run into this issue.
> Match the MAX_PASSWORD value in bouncer.h

- include/bouncer.h
- src/objects.c
- src/server.c
- test/ssl/test.ini
- test/test_ssl.py
verify-full requires to compare hostname against the server certificate. Looks like we pass the entire multi-host string as the hostname which causes failure with connection establishment.
Fixes #1300
> SSL verify-full mode is broken with multi-host configuration.

- src/pam.c
Based on the discussion in #1054
Change "queue full" message in pam_auth_begin() from debug to warning. In current code (with sleep) this can easily become a bottleneck. Displaying the warning will save hours of debugging when users are trying to diagnose pgbouncer unresponsiveness.
> Change PAM queue full debug message to warning

- .cirrus.yml
- Makefile
- doc/config.md
- etc/pgbouncer.ini
- test/asynctest.c
- test/hba_test.c
- test/pgbouncer_hba.conf
- test/pgident.conf
I noticed some files weren't following the .gitattributes whitespace rules, so I fixed those and also added an automatic check for it. (One possible problem is that this check only works in a git checkout. Do we need to support other cases?)
Also, some of that would have been caught by the uncrustify check, but that wasn't run on some files, so I added that as well.
> Whitespace checks and fixes

- doc/config.md
- etc/pgbouncer.ini
- include/common/scram-common.h
- include/scram.h
- src/common/scram-common.c
- src/main.c
- src/scram.c
This PR makes the number of scram iterations that are used to generate SCRAM keys configurable. This is an attempt to partially resolve #1335 by allowing people to use a lower iteration count to reduce the amount of computation that is needed for PgBouncer to process a client authentication request.
> Make SCRAM Iterations Runtime Configurable

- doc/usage.md
- src/admin.c
- test/test_admin.py
Allows KILL to operate on all databases similar to RECONNECT.
> Teach KILL command to take an optional db argument

- .cirrus.yml
Reactivate the Debian/Ubuntu tasks that were commented out in 92b4645, setting them to trigger manually.  This was already done for the other tasks in commit 0738448.  There I wrote, "this does not appear to work for matrix elements inside a task", but this appears to work now (or it worked back then but I didn't do it correctly).
In the re-enabled tasks, raise the Ubuntu version from 20.04 to 22.04, like the change in commit ef611b5, and where it was already 22.04 to now 24.04.
The clang variant is removed.  This is already covered by the FreeBSD task now.
The variant that runs Valgrind against PostgreSQL 9.6 is removed. This was originally meant to handle the non-SCRAM code paths, but those PostgreSQL versions are long obsolete.
Also update the PGVERSIONs of the Debian tasks.  Those …
> ci: Re-enable commented out Debian/Ubuntu tasks, with manual trigger

- .cirrus.yml
- Makefile
- doc/Makefile
- test/Makefile
- test/ssl/Makefile
This changes `make dist` to directly use `git archive`, rather than the custom shell script it currently runs.
This is to make the creation of the distribution tarball more reliable, as this does not require manual maintenance of various `*_DIST` make variables.  Eventually, it will also make the distribution tarball more directly traceable to the git repository.  For the time being, we still include files produced by `autogen.sh` in the tarball, for ease of use. (This could go away when the meson build system (#1077) is ready.)
The techniques used are the same as in postgres/postgres@619bc23a1a2.
(This required getting rid of git submodules, since `git-archive` does not support submodules.)
> make dist uses git archive

- test/test_misc.py
One test was using a time zone name "Portugal", but that doesn't exist anymore, at least in Ubuntu 24.04 and the upcoming Debian trixie, possibly others as well, causing those tests to fail.  Replace with "Europe/Lisbon".
Compare:
* https://packages.ubuntu.com/jammy/all/tzdata/filelist vs. https://packages.ubuntu.com/noble/all/tzdata/filelist
* https://packages.debian.org/bookworm/all/tzdata/filelist vs. https://packages.debian.org/trixie/all/tzdata/filelist
> Fix test using obsolete time zone name

- etc/mkauth.py
The `mkauth.py` script previously generated auth_file entries with three quoted fields: `"user" "password" ""`.
The third field was a leftover from an old postgresql flat-file format (`pg_pwd`) that included a "valid until" field in addition to the username and password.
This format was originally used to allow pgbouncer to directly read the `pg_pwd` file, maintaining compatibility during a transition period.
However, the `pg_pwd` file has long been removed, and pgbouncer ignores all fields after the second one.
Removing this unused field simplifies the file format, aligns with pgbouncer documentation and common usage, and helps prevent confusion when managing auth_file contents.
Fixes: #1351
> Remove obsolete third field from auth_file entries in mkauth.py

- .cirrus.yml
This was forgotten in commit e0d58b5 for the manually triggered tasks. The new tests have been failing in the meantime.
> ci: Add socat installation to Red Hat and Alpine tasks

- .cirrus.yml
The idea is to have these jobs test more features and have the configuration be similar to what the downstream packagers are using, so it's more realistic overall.
This adds --with-pam to the Red Hat jobs, and --with-cares to RHEL >=9.  Also --with-cares to Alpine.
The FreeBSD and macOS jobs appear to be in good shape in this respect already (no c-ares in either case in the downstream packages).
> ci: Add more configure args to Red Hat and Alpine jobs

- Makefile
What do you think about having pytest report skipped tests by default at the end of the run, like in the attached patch. I have found this useful to analyze exactly what certain CI tasks test and don't test. So we could enable it on CI only. But I imagine it could also be useful for local development, if you don't realize that there are certain tests that you haven't activated.
> Have pytest report skipped tests by default

- .cirrus.yml
Since we dropped RHEL 7 a while ago, we can use dnf across all variants.
> ci: Switch commands from yum to dnf

- .cirrus.yml
This requires installing several openldap* packages (openldap-devel for building, openldap-clients and openldap-servers for the tests), of which openldap-servers is in some extra repository, the name of which varies across versions.
toward fixing #1375
> ci: Enable LDAP on Red Hat tasks

- .cirrus.yml
- test/start_openldap_server.sh
The script start_openldap_server.sh hardcoded /bin/bash, which does not exist on FreeBSD.  The script works just fine with /bin/sh, so use that instead.
Also, generalize the search for various openldap-related paths to handle the FreeBSD installation location.
With that fixed, we can enable LDAP on the CI FreeBSD task.  We need to install openldap client and server packages for that.
toward fixing #1375
> Fix LDAP tests on FreeBSD

- .cirrus.yml
- test/start_openldap_server.sh
- test/test_auth.py
We need to look for the LDAP files in various locations.  I copied the locations used by PostgreSQL for its LDAP tests; this supports both Homebrew and MacPorts locations.  (The macOS native LDAP libraries are not supported by neither PgBouncer nor PostgreSQL.)  Then we can un-skip the tests on macOS and enable them in CI.
toward fixing #1375
> Enable LDAP tests on macOS

- .cirrus.yml
- README.md
LDAP should be tested on more platforms. Let's look at the test runs ...
- Red Hat: build ok, tests fail
- Alpine: build ok, tests ok
- FreeBSD: build ok, tests fail
- macOS: build fails
- Windows: build fails
> ci: Enable LDAP on more platforms

- include/common/postgres_compat.h
PgBouncer already has portable definitions for the equivalent of `pg_nodiscard` and `pg_noreturn`, so we use them instead of reproducing the complicated definitions from PostgreSQL.
(Some of this will change in PostgreSQL 19 and beyond, as C11 and beyond gets adopted. Maybe in the long run, some of these things can be unified between PostgreSQL and PgBouncer. For now, this is just a simplification to use the existing facilities.)
> Simplify some attributes in postgres_compat.h

- .cirrus.yml
This saves installing a bunch of extra packages, thus saving download bandwidth and CPU time.
The "Formatting checks & linting" task needs a few more packages installed that were previously pulled in indirectly.
---
Examples:
before:
```
0 upgraded, 40 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.4 MB of archives.
2 upgraded, 186 newly installed, 0 to remove and 0 not upgraded.
Need to get 192 MB of archives.
0 upgraded, 160 newly installed, 0 to remove and 0 not upgraded.
Need to get 127 MB of archives.
```
after:
```
0 upgraded, 32 newly installed, 0 to remove and 0 not upgraded.
Need to get 13.0 MB of archives.
2 upgraded, 123 newly installed, 0 to remove and 0 not upgraded.
Need to get 159 MB of archives.
0 upgraded, 85 newly installed, 0 to remove and 0 not …
```
> ci: Use apt-get install with --no-install-recommends
