test/test.sh
- Replace `seq a b` with {a..b}, and auto-upgrade to bash if shell does
not support range expansion (DASH on Ubuntu)
- Replace ipfw with pf; (MacOS 10.7+, *BSD)
- Replace `echo -n` with `printf` (MacOS)
- Change to test directory before starting
- Provide aproximate compatibility between MacOS and Linux options for
sed and nc
- Auto-populate userlist.txt
Tested on MacOS 10.10, Ubuntu 14, OpenBSD 5.7
=> Adapt system tests to work with modern BSD and MacOS

doc/config.rst
Relates to:
* https://github.com/pgbouncer/pgbouncer/issues/77
* https://github.com/pgbouncer/pgbouncer/issues/70
=> Document version requirement for hba auth_type

src/admin.c
=> Add paused and disabled field on the show databases command

src/admin.c
Displaying the time since query_time for all sockets in `SHOW SOCKETS` makes it possible to detect whether a single slow transaction is distorting a pool's max-wait time or if there is more general slowdown.
This PR adds columns named `wait` and `wait_us` to `socket_row`, displaying the number of elapsed seconds and microseconds since the socket's current query was started. If there is no outstanding query on the socket, 0 is shown in both fields. This naming and format was chosen to complement the existing maxwait and new (see PR 212) maxwait_us fields in `SHOW POOL`, which shows the same field in the same way, but only for the front socket.
=> Add per-socket wait times to SHOW SOCKET.

doc/config.rst, include/bouncer.h, src/client.c, src/loader.c, src/main.c
Please review and test this patch. I was able to make it working on my laptop, but it requires more testing. Thanks.
=> Global management of 'auth_user'

src/server.c
=> Receiving NotificationResponse asynchronously should not raise warning

etc/mkauth.py
=> Port mkauth.py to Python 3

src/main.c
a online restart -> an online restart
=> Fix usage typo

src/objects.c
The message "unclean server" is logged if the client connection is
closed while the server is not in "ready" state.  That can be if the
server is in a transaction block, because then we can't reset the
server to non-transaction state other than by closing it.  So this
message can happen in relatively normal use, and it's pretty unclear
and a bit scary.  So this change attempts to make the message a bit
more precise and document, at least in the code, what it means.
=> Make "unclean server" message clearer

src/client.c
When using md5 authentication with a plain-text password, the old code
did the inner md5() call and overwrote the password in the in-memory
structures with that result.  That makes sense if md5 is the only
authentication method you ever use in an instance, because then you
don't need to do that call on every client login.  But with hba, a
different authentication method could be used next time, but this
behavior destroys the plain-text password.  For example, logging in
with md5 first will make a subsequent scram login fail, but not vice
versa.  To fix, don't cache the md5() result but just compute it every
time it is needed.  (We could in theory create a separate field for
caching the md5() output, but since this method is obsolescent, let's
not bother.)
=> Fix md5 authentication overwriting user name in memory

doc/config.md, src/main.c, src/objects.c, src/pooler.c
matches PostgreSQL 14 feature (postgres/postgres@c9f0624bc2f544baacafa38e3797d5323401d039)
=> Add support for abstract Unix-domain sockets

doc/config.md, include/bouncer.h, include/pktbuf.h, test/test.ini, test/test.sh
This consolidates various requests in this area, together with tests and more code comments.
=> Increase MAX_PASSWORD and MAX_USERNAME

src/objects.c
=> Fixes segmentation fault in disconnect_server when server is NULL

doc/usage.md, src/admin.c
Implements the feature request at https://github.com/pgbouncer/pgbouncer/issues/167
=> Add application_name to SHOW CLIENTS/SERVERS/SOCKETS output

.cirrus.yml, .flake8, dev_requirements.txt, doc/filter.py, etc/mkauth.py, pyproject.toml, test/conftest.py, test/stress.py, test/test_auth.py, test/test_cancel.py, test/test_limits.py, test/test_misc.py, test/test_operations.py, test/test_ssl.py, test/test_timeouts.py, test/utils.py
This uses `black` and `isort` to get consistent codestyle in all our python
files in the repo.
It also adds the `flake8-bugbear` plugin to `flake8`
=> Autoformat python code

.cirrus.yml, src/hba.c, src/stats.c
currently failing, causing checks of new PRs to fail
=> Fix Cirrus macOS

src/main.c
Fix https://github.com/pgbouncer/pgbouncer/issues/825
Thank you!
=> Don't exit with non-zero status on SIGTERM

NEWS.md, configure.ac
(cherry picked from commit 05e78bd1743fff2b79a654914d1ced7f697a7afd)
=> Cherry pick 1.19.1 changelog

.editorconfig
We also use tabs there, but they were missed in the file.
=> Also configure editorconfig to use tabs for .h files

etc/pgbouncer.ini
I forgot to address the review comment mentioning this when I fixed the
failing tests.
=> Update pgbouncer.ini to match changes made in #948

test/README.md
Found some grammatical errors, when i was reading through test/README.md .
=> Typo in test/readme

doc/config.md, doc/usage.md
Fixes #1008
Fixes #959
Fixes #643
=> Various doc updates

doc/config.md
=> #1035 - patch to indicate pem certificates / keys are usable by pgbouncer

.cirrus.yml
=> Fix macOS in CI 

doc/config.md, test/test_ssl.py
=> Remove mention in docs of invalid alias for server_tls_protocols

src/client.c
Fixes #1212
Introduced by #1007
=> Fix possible null dereference

doc/config.md, test/test_misc.py
Closes https://github.com/pgbouncer/pgbouncer/issues/1163
=> Update auth_query example

test/test_prepared.py
Sometimes a test_prepared_failed_prepare_pipeline fails due to an
unimportant race condition[1]. This hopes to fix that.
[1]: https://cirrus-ci.com/task/4548060467953664?logs=test#L46
=> Try to fix flaky test

Makefile, README.md, config.mak.in, configure.ac, etc/pgbouncer.ini, include/bouncer.h, src/client.c, src/ldapauth.c, src/main.c, test/utils.py
Some cleanup for commit cabe794:  Sort the newly added code a bit more sensibly in the existing code, instead of just tacking it on at the end or in random positions.  Simplify the build integration.  Fix a typo.
=> Code tidying for LDAP support
